#!/bin/bash

read _ U N S Y I Q W _ < /proc/stat
I=$((Y + I))
T=$((U + N + S + Q + W + I))

Z=/dev/shm/i3blocks_cpu.prev
if [[ -f $Z ]]; then
    read PT PI < $Z
    D=$((T - PT))
    X=$((I - PI))
    P=$((100 * (D - X) / D))
else
    P=0
fi
echo $T $I > $Z

printf '<span>\uf4bc</span> %2d%%\n' $P
echo

if   ((P >= 90)); then echo "#FF5555"
elif ((P >= 50)); then echo "#FFFF00"
else                   echo "#FFFFFF"
fi
