#!/bin/bash

read T U <<< $(free -m | awk '/^Mem:/ {print $2, $3}')
P=$((100 * U / T))

printf '<span>\uefc5</span> %2d%%\n' "$P"
echo

if   ((P >= 90)); then echo "#FF5555"
elif ((P >= 70)); then echo "#FFFF00"
else                   echo "#FFFFFF"
fi
