#!/bin/bash

exec > /tmp/i3.init
exec 2>&1

PATH="$HOME/.config/scripts:$PATH"

# Touch screen
{
   ID=$( xinput list --id-only 'Wacom HID 4941 Finger touch' )
   xinput map-to-output $ID eDP-1
} &


# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
xss-lock --transfer-sleep-lock -- i3lock --nofork -c 000000 &
xautolock -detectsleep -time 10 -locker "i3lock -c 000000" -notify 30 -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'" &

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
nm-applet &
solaar &
xsetroot -solid "#000" &

# Touchpad gestures
fusuma -d &

# Monitors resolutions
moni &

wait

