#!/bin/bash

CLIENT=main
SESSION=main
JOB=run

while getopts "c:s:kdr" opt; do
    case ${opt} in
        c) CLIENT=$OPTARG  ;;
        s) SESSION=$OPTARG ;;
        k) JOB=kill        ;;
        d) JOB=daemon      ;;
        r) JOB=reuse       ;;
    esac
done

shift $((OPTIND-1))

case $JOB in
    run | reuse | daemon)
        kak -d -s $SESSION &> /dev/null &
        ;;&
    run)
        exec kak -c $SESSION -e "try 'rename-client $CLIENT'" $@
        ;;
    reuse)
        echo "reuse-create-client $CLIENT '$(realpath $1)'" | kak -p $SESSION
        ;;
    kill)
        echo kill | kak -p $SESSION 2>/dev/null
        kak -clear
        ;;
esac
