#!/bin/zsh

#### Configs
# Basics
export EDITOR=code
export BROWSER=google-chrome-stable
export TERMINAL=urxvtc

path+=("$HOME/.local/bin/i3")
export PATH



#### Aliases
# Basics
alias y='yay --nodiffmenu'



#### Ending
# Common
source ~/.config/zsh/profile

# Xorg
[[ -z "$DISPLAY" ]] && [[ "$(tty)" == "/dev/tty1" ]] && exec startx



