#!/bin/zsh

#### Configs
# Basics
export EDITOR=code
export BROWSER=google-chrome-stable
export TERMINAL=urxvtc



#### Aliases
# Basics
alias y='yay --nodiffmenu'



#### Ending
# Common
source ~/.config/zsh/zshrc

path+=("$XDG_CONFIG_HOME/scripts/i3")
export path

# Xorg
[[ -z "$DISPLAY" ]] && [[ "$(tty)" == "/dev/tty1" ]] && exec startx



