#!/bin/zsh

# If not running interactively, don't do anything
[[ $- != *i* ]] && return



#### Configs
# Basics
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}

typeset -gxU path=(
    "."
    "$path[@]"
    "$XDG_CONFIG_HOME/scripts"
    "$HOME/.local/bin"
)

# nnn
export NNN_OPENER=${NNN_OPENER:-scope}
export GUI=1



#### Zsh
# History
HISTSIZE=10000
SAVEHIST=10000
HISTFILE="$XDG_CACHE_HOME/zsh_history"

# Prompt
setopt PROMPT_SUBST
autoload -U colors && colors
PROMPT="%{$reset_color$fg[blue]%}%n@%m%{$fg[green]%} %(!.%1~.%~) \$(prompt_git_status)%{$reset_color%}$ "

prompt_git_status() {
    local BRANCH="$( git rev-parse --abbrev-ref HEAD 2>/dev/null )"
    
    if [[ -n "$BRANCH" ]]; then
        local STATUS="%{$fg[yellow]%}"
        git diff --quiet --ignore-submodules HEAD 2>/dev/null || STATUS="%{$fg[red]%}"
        printf '%b' "${STATUS}(${BRANCH}) "
    fi
}

# Plugins
fzf-history-widget() {
    local RES=$( fc -rln 1 | perl -ne 'print if !$seen{$_}++' | fzf --height=11 --tiebreak=index --info=hidden --reverse --query=${LBUFFER} )
    [[ -n "$RES" ]] && BUFFER="$RES" && zle end-of-line
    zle reset-prompt
}
zle -N fzf-history-widget

fzf-files-widget() {
    local RES=$( fd -HI | fzf --height=11 --info=hidden --reverse --query="" )
    LBUFFER="$LBUFFER$RES"
    zle reset-prompt
}
zle -N fzf-files-widget

# Bindings
typeset -A key
key=(
    BackSpace  "${terminfo[kbs]}"
    Home       "${terminfo[khome]}"
    End        "${terminfo[kend]}"
    Insert     "${terminfo[kich1]}"
    Delete     "${terminfo[kdch1]}"
    Up         "${terminfo[kcuu1]}"
    Down       "${terminfo[kcud1]}"
    Left       "${terminfo[kcub1]}"
    Right      "${terminfo[kcuf1]}"
    PageUp     "${terminfo[kpp]}"
    PageDown   "${terminfo[knp]}"
)

bindkey "${key[Home]}" beginning-of-line
bindkey "${key[End]}"  end-of-line
bindkey "${key[Up]}"   up-line-or-search
bindkey "${key[Down]}" down-line-or-search

bindkey '^R'    fzf-history-widget
bindkey '^F'    fzf-files-widget

# Others
stty stop undef       # Disable ctrl-s to freeze terminal.



#### Aliases
# Basics
alias   ls='ls --color=auto'
alias   ll='ls -lh'
alias   la='ls -lha'

# Git
alias    g='git'
alias   ga='git add'
alias  gaa='git add --all'
alias   gc='git commit -v -m'
alias  gc!='git commit -v --no-edit --amend'
alias  gca='git commit -v -a -m'
alias gca!='git commit -v -a --no-edit --amend'
alias  gco='git checkout'
alias  gcm='git checkout master'
alias   gd='git diff'
alias  gdc='git diff --cached'
alias  gds='git diff --staged'
alias   gf='git fetch'
alias  gfa='git fetch --all --prune'
alias  gcf='git config --list'
alias  glo="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
alias   gb='git branch'
alias   gm='git merge'
alias   gp='git push'
alias   gl='git pull'
alias  grh='git reset'
alias grhh='git reset --hard'
alias  gst='git status'
alias  grb='git rebase'
alias  gsh='git show'

# Windows
alias    n='nnn -cod'
alias tmux='tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf'

# Editor
alias   kk='kak-launcher'
alias  kkf='kak-launcher -k'

# Configs
alias   hh='GIT_DIR=$HOME/.cfg/ GIT_WORK_TREE=$HOME'

