#!/bin/zsh

#### Configs
# Common
source ~/.config/zsh/zshrc

# Basics
export EDITOR=code
export BROWSER=google-chrome-stable
export TERMINAL=urxvtc

path+=("$XDG_CONFIG_HOME/scripts/i3")


#### Aliases
# Basics
alias y='yay --nodiffmenu'


#### Ending
# Xorg
[[ -z "$DISPLAY" ]] && [[ "$(tty)" == "/dev/tty1" ]] && exec startx
