#!/bin/bash
set -e

# base
apt update
apt purge -y snapd cloud-init
unminimize
ubuntu-drivers autoinstall

apt install -y curl wget git zsh tmux jq ca-certificates nftables neovim fdisk gdisk netplan.io
apt install -y fonts-noto-color-emoji fonts-noto fonts-symbola xorg i3 i3blocks i3lock xautolock dmenu alacritty rofi feh picom maim
apt install -y wireplumber pipewire pipewire-audio pipewire-pulse pipewire-audio-client-libraries playerctl blueman bluez

wget "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" -O /tmp/chrome.deb
wget "https://api2.cursor.sh/updates/download/golden/linux-x64-deb/cursor/latest" -O /tmp/cursor.deb
dpkg -i /tmp/chrome.deb /tmp/cursor.deb

# docker
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu  $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
